models.py
from app import db
from datetime import datetime
from flask_security import UserMixin, RoleMixin
import re


def slugify(s):  # Функция поиска и исправлению url страниц.
    pattern = r'[^\w+]'  # Ищет исключения
    return re.sub(pattern, '-', str(s))  # Заменяет их на дефис


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')))


# Класс по созданию постов, в базу данных.
# Создаем параметры колонок для хранение в базе данных.
class Post(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created_data = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):  # args это Список (одна звездёочка). kwargs именнованные словари.
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))



    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<post id: {}, title: {}>'.format(self.id, self.title)

# Класс миграции
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '{}'.format(self.name)



#  Создаем базу для юзеров.
roles_users = db.Table('roles_users',
                     db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                     db.Column('role_id', db.Integer, db.ForeignKey('role.id')))



# Роутинг пользователей
class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))



class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PosstForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore, Security, current_user
from flask import  redirect, url_for, request
from flask_admin import Admin, AdminIndexView




app = Flask(__name__)
app.config.from_object(Configuration)
db = SQLAlchemy(app)


migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)



from models import *

# Доступ к админке

class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


# Класс создания слага (человекопободнойссылки)
class BaseModeView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModeView, self).on_model_change(form, model, is_created)


class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass



class PostAdminView(AdminMixin, BaseModeView):
    form_columns = ['title', 'body', 'tags']


class TagAdminView(AdminMixin, BaseModeView):
    form_columns = ['name', 'posts']



admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))  # Подключили админку
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))



# Создаем user
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
<<<<<<< HEAD
#  Бета версия 
=======
# Стабильная версия ! Тут должно работать ВСЁ 
>>>>>>> main
from app import app
from app import db
import view
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')


if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post, Tag
from flask import request
from .forms import PosstForm
from app import db
from flask import redirect
from flask import url_for
from flask_security import login_required




posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST', 'GET'])
@login_required  # Декоратор ограничение права из библиотеки flask_security
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Ошибочка')


        return redirect( url_for('posts.index') )


    form = PosstForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PosstForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))


    form = PosstForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)



@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1



    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))  # Метод поиска
    else:
        posts = Post.query.order_by(Post.created_data.desc())

    pages = posts.paginate(page=page, per_page=5)


    return render_template('posts/index.html', posts=posts, pages=pages)




@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">

        {% for field in form %}

            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}

        <button type='submit' class='btn btn-success'>Create post </button>

    </form>
</div>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    EDIT
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}

<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug = post.slug) }}" method="POST">

        {% for field in form %}

            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}

        <button type='submit' class='btn btn-success'>EDIT </button>

    </form>
</div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Блюпринт
{% endblock %}

{% block content_title %}
Бложек
{% endblock %}

{% block content %}

{% for post in pages.items %}
<p>
    <a href="{{ url_for('posts.post_detail', slug = post.slug) }}" class="btn btn-primary">{{ post.title }}</a>
</p>
{% endfor %}

<nav aria-label="...">
  <ul class="pagination">

      <li {% if not pages.has_prev %} class="disabled" {% endif %}>
        <a href="./?page={{ pages.prev_num }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
    </li>

      {% for page in pages.iter_pages() %}

            <li {% if page == pages.page %} class="active" {% endif %}>

                <a href="./?page={{ page }}">{{ page }} <span class="sr-only">(current)</span></a>
      {% endfor %}





    </li>

        <li {% if not pages.has_next %} class="disabled" {% endif %}>
        <a href="./?page={{ pages.next_num }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
    </li>



  </ul>
</nav>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}


{% block content_title %}

    {{ post.title }}

{% endblock %}



{% block content %}
    {% for tag in tags %}
     <a href="{{ url_for('posts.tag_detail', slug = tag.slug) }}"><span class="label label-primary">{{ tag.name }}</span></a>

    {% endfor %}

<div class="main-content">
    {{ post.body }}
     </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:

{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug = post.slug) }}">{{ post.title }}</a>
        </div>

    {% endfor %}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="http://bootstraptema.ru/snippets/style/2015/bootswatch/bootstrap-paper-v3.3.6.css" media="screen">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>
        {% block title %}

        {% endblock %} | Flask Blog

    </title>
  </head>
  <body>
  <!-- Начало меню -->
  <nav class="navbar navbar-inverse">
      <div class="container-fluid">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('index') }}">Main</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
              <ul class="nav navbar-nav">
                  <li class="active"><a href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a></li>
                  <li><a href="#">Link</a></li>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Action</a></li>
                          <li><a href="#">Another action</a></li>
                          <li><a href="#">Something else here</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Separated link</a></li>
                          <li class="divider"></li>
                          <li><a href="#">One more separated link</a></li>
                      </ul>
                  </li>
              </ul>
              <!-- ПОИСК -->
              <form class="navbar-form navbar-left" role="search" method="GET">
                  <div class="form-group">

                      <input type="text" class="form-control" placeholder="Search" name="q"
                             value="{{ request.args.get('q', '') }}">

                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
              </form>

              <ul class="nav navbar-nav navbar-right">
                  <!--<li><a href="{{ url_for('posts.create_post') }}">+ New Post</a></li>-->
                  <li>
                      {% if current_user.has_role('admin') %}
                      <a href="/admin">Admin</a>
                      {% endif %}
                  </li>


              </ul>
          </div>
      </div>
  </nav>
  <!-- Конец меню -->
  <div class="container">
      <div class="row">
          <h1>
              {% block content_title %}

              {% endblock %}
          </h1>

      </div>
        {% block content %}

  {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <script src="http://bootstraptema.ru/snippets/style/2015/bootswatch/jquery-1.10.2.min.js"></script>
  <script src="http://bootstraptema.ru/snippets/style/2015/bootswatch/bootstrap.min.js"></script>
  <script src="http://bootstraptema.ru/snippets/style/2015/bootswatch/custom.js"></script>

  </body>
</html>

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="fleshes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content_title %}

<center>{{ ('Login') }}</center>

{% endblock %}



{% block content %}

<div class="col-md-offset-4 col-md-4">
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email, class='form-control') }}
  {{ render_field_with_errors(login_user_form.password, class='form-control') }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit, class='btn btn-success') }}
</form>
{% include "security/_menu.html" %}
</div>
{% endblock %}




{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit) }}
</form>
{% include "security/_menu.html" %}